# Generated by Django 4.0.3 on 2022-03-30 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="salers",
            new_name="seller",
        ),
    ]
