# Generated by Django 4.0.3 on 2022-03-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('manager', 'Manager'), ('seller', 'Seller'), ('technician', 'Technician')], max_length=15),
        ),
    ]
